{% set name = "momlevel" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/momlevel-{{ version }}.tar.gz
  sha256: d7e83bdc2fd71523f90a64bbca06cd1a445e3664836277b54e1442563e4c5e44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-git-versioning
  run:
    - python >=3.8
    - importlib-metadata <5.0.0
    - nc-time-axis
    - netcdf4
    - numpy
    - scikit-learn
    - xarray
    - xgcm

test:
  imports:
    - momlevel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jkrasting/momlevel
  summary: Tools to diagnose sea level in the MOM Ocean Model
  description: |
    momlevel is a Python package in the public domain that provides
    documentation and routines for analyzing sea level and related
    quantities in MOM6-class models. The package initially focuses
    on global and local steric sea level change in Boussinesq configurations.
  license: LicenseRef-PUBLIC-DOMAIN
  license_file: LICENSE.txt
  doc_url: https://momlevel.readthedocs.io/
  dev_url: https://github.com/jkrasting/momlevel

extra:
  recipe-maintainers:
    - jkrasting
