{% set name = "momlevel" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/momlevel-{{ version }}.tar.gz
  sha256: ad8ac48ba35eb326177d4daa15562a45e15785fde8d59017a45ca8ed08976c66

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-git-versioning
  run:
    - python >={{ python_min }}
    - importlib-metadata <5.0.0
    - nc-time-axis
    - netcdf4
    - numpy
    - scikit-learn
    - xarray
    - xgcm

test:
  imports:
    - momlevel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jkrasting/momlevel
  summary: Tools to diagnose sea level in the MOM Ocean Model
  description: |
    momlevel is a Python package in the public domain that provides
    documentation and routines for analyzing sea level and related
    quantities in MOM6-class models. The package initially focuses
    on global and local steric sea level change in Boussinesq configurations.
  license: LicenseRef-PUBLIC-DOMAIN
  license_file: LICENSE.txt
  doc_url: https://momlevel.readthedocs.io/
  dev_url: https://github.com/jkrasting/momlevel

extra:
  recipe-maintainers:
    - jkrasting
